[package]
name = "break-infinity"
version = "0.1.0"
edition = "2018"

authors = ["Redfire <redfire75369@hotmail.com>"]
license = ""
description = ""
homepage = ""
documentation = ""
repository = ""
readme = ""

#keywords = ""
#categories = ""

exclude = [
	".editorconfig",
	".gitignore"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.5.2"
rand = "0.8.0"
